import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import editionsABI from "@zoralabs/nft-drop-contracts/dist/artifacts/ERC721Drop.sol/ERC721Drop.json"
import { Header } from '../components/Header'
import { Footer } from '../components/Footer'
import { useState } from 'react'
import { ethers, BigNumber } from 'ethers'
import { useContractWrite, useContractRead, useWaitForTransaction } from 'wagmi'
import { useAppContext } from "../context/useAppContext"
import MintQuantity from '../components/MintQuantity'
import PostMintDialog from '../components/PostMintDialog'

const heavenly = '#ff0000'

const Mint: NextPage = () => {

    const { mintQuantity, setMintQuantity } = useAppContext()

    // ZORA NFT Edition "purchase" Write
    const perMintPrice = 0.33
    const totalMintPrice = String(mintQuantity.queryValue * perMintPrice)
    const mintValue = BigNumber.from(ethers.utils.parseEther(totalMintPrice)).toString()
    console.log("mint VAlue", mintValue)


    const { data: totalSupplyData, isLoading, isSuccess, isFetching  } = useContractRead({
        addressOrName: "0x6d9fb8a25eed14e0378cd7e07f00ef4f409d9d7c", // Clasick Collection
        contractInterface: editionsABI.abi,
        functionName: 'totalSupply',
        args: [],
        watch: true,
        onError(error) {
            console.log("error: ", error)
        },
        onSuccess(data) {
            console.log("success! --> ", totalSupplyData)
        }  
    })    

    const totalSupply = totalSupplyData ? totalSupplyData.toString() : "loading"

    // useContractWrite Mint Call
    const { data: mintData, isError: mintError, isLoading: mintLoading, isSuccess: mintSuccess, status: mintStatus, write: mintWrite  } = useContractWrite({
        addressOrName: "0x6d9fb8a25eed14e0378cd7e07f00ef4f409d9d7c", // Classick Collection
        contractInterface: editionsABI.abi,
        functionName: 'purchase',
        args: [
            mintQuantity.queryValue
        ],
        overrides: {
            value: mintValue
        },
        onError(error, variables, context) {
            console.log("error", error)
        },
        onSuccess(cancelData, variables, context) {
            console.log("Success!", cancelData)
        },
    })
    
    // useWaitforTransaction
    const { data: mintWaitData, isError: mintWaitError, isLoading: mintWaitLoading } = useWaitForTransaction({
        hash:  mintData?.hash,
        onSuccess(holderMintWaitData) {
            console.log("txn complete: ", mintWaitData)
            console.log("txn hash: ", mintWaitData.transactionHash)
        }
    })           

    return (
        <div className='flex flex-col justify-center h-screen min-h-screen'>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="flex flex-col flex-wrap items-center justify-center h-full ">
                <div className="flex flex-col flex-wrap items-center">
                    <div className={`text-center p-8 mt-5 sm:mt-0 bg-white border-[16px] border-double border-[${heavenly}] font-gothiccc text-5xl sm:text-7xl h-fit w-fit flex flex-row justify-center`} >
                    {"1Take"}
                    </div>
                    <div className={`mt-10 mb-10 p-8  border-[16px] border-[${heavenly}] border-double bg-white min-w-fit sm:min-w-min  w-8/12 xl:w-6/12 h-fit  `}>
                        <div className="flex flex-row justify-center w-full text-4xl text-center h-fit " >
                        Rockie Fresh - Watch It Grow | 1Take Performance
                        </div>
                        <div className="flex flex-row justify-center w-full mt-8">
                            <MintQuantity colorScheme={heavenly}/>
                            <button 
                            className="flex flex-row justify-self-start  text-2xl  p-3  w-fit h-fit border-2 border-solid border-[#ff0000] hover:bg-[#ff0000] hover:text-white"
                            onClick={() => mintWrite()}   
                            >
                            Mint
                            </button>
                        </div>
                        <PostMintDialog 
                            publicTxnLoadingStatus={mintWaitLoading}
                            publicTxnSuccessStatus={mintStatus}
                            publicTxnHashLink={mintWaitData}
                            colorScheme={heavenly}
                        />               
                        { mintWaitLoading == true ? (
                            <div className="flex flex-row flex-wrap justify-center mt-10 text-xl sm:text-2xl ">           
                            <img
                                className="bg-[#40bedc] p-1 rounded-3xl mb-8 w-fit flex flex-row justify-self-center items-center"
                                width="20px" 
                                src="/SVG-Loaders-master/svg-loaders/tail-spin.svg"
                            />
                            <div className="w-full text-center">
                                mint price: 0.33 Ξ
                            </div>                        
                                <div className="w-full text-center">
                                    {`${totalSupply}` + " minted so far . . ."}
                                </div>
                            </div>   
                            ) : (                  
                            <div className="flex flex-row flex-wrap justify-center mt-10 text-xl sm:text-2xl ">
                            <div className="w-full text-center">
                                mint price: 0.33 Ξ
                            </div>                
                                <div className="w-full text-center">
                                    {`${totalSupply}` + " minted so far . . ."}
                                </div>
                            </div>                                          
                        )}                         
                        <Link href="/">
                            <a className="flex flex-row justify-center mt-5 text-xl text-center">
                            ← HOME
                            </a>
                        </Link>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Mint
